version: '3.7'
services:
  firebase-emulator:
    build:
      context: ./firebase-emulator
    ports:
      - "4000:4000"
      - "8080:8080"
  example1:
    build:
      context: ./example1
    env_file:
      - ./.env
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
     - firebase-emulator
  example2:
    build:
      context: ./example2
    env_file:
      - ./.env
    environment:
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
     - firebase-emulator